### ISSUE TITLE
Notification when an existing user is invited to a case (new or existing)

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/frontend#281]
As of today we have an email notification to NEW Unee-T users once there are invited to their first case for their role in a given unit.

We do NOT yet have a notification mechanism to inform an existing Unee-T user that he has been invited to a new (or existing) case for a unit he or she has a role in.

We need to fix this as this is a huge problem: users have no way to be notified of what's happening unless they check all the units they have a role in in Unee-T (impractical at best).

**Comment by kaihendry** [comment]
We need the steps to simulate this event on arn:aws:sns:ap-southeast-1:812644853088:atest ? And then add the event payload here.

**Comment by kaihendry** [comment]
Created https://github.com/unee-t/sns2email as a repo to tackle this.

**Comment by franck-boullier** [comment]
@kaihendry give me a couple of hours to get back to you on that...

I need to explore a few ideas I have to do this efficiently...

Easiest/most efficient way might be to create a dedicated table to store this in the BZ database and then trigger something using lambda each time a user is invited to a case.

**Comment by franck-boullier** [comment]
@kaihendry Our lambda is now triggered each time a user is invited or assigned to a case.
This has been implemented in the DEV/Staging, Demo and Prod environment

# How it works:
I have updated the JSON message generated from our lambda function.
The notification now include information about notification type so we can differentiate what we do for each type of notifications.

The various types of notifications are described in the table `ut_notification_types` in the BZ database.

# Examples of the payload:

## A case is created: 
We generate 3 notifications

### notification that a case has been created:
{ "notification_type": "case_updated", "bz_source_table": "ut_notification_messages_cases", "notification_id": "195", "created_datetime" : "2018-06-11 14:24:52", "unit_id" : "289", "case_id" : "61975", "user_id" : "100", "update_what" : "New Case"}

### notification that something happened on that case:
{ "notification_type": "case_updated", "bz_source_table": "ut_notification_messages_cases", "notification_id": "196", "created_datetime" : "2018-06-11 14:24:52", "unit_id" : "289", "case_id" : "61975", "user_id" : "100", "update_what" : "New Message"}

### notification that a user has been assigned to that case:
{ "notification_type": "case_assignee_new", "bz_source_table": "ut_notification_case_assignee", "notification_id": "4", "created_datetime" : "2018-06-11 14:24:52", "unit_id" : "289", "case_id" : "61975", "invitor_user_id" : "100", "assignee_user_id" : "134"}

## A user is invited to a case:
We generate 2 notifications
### notification that something happened on that case:
{ "notification_type": "case_updated", "bz_source_table": "ut_notification_messages_cases", "notification_id": "202", "created_datetime" : "2018-06-11 14:50:29", "unit_id" : "289", "case_id" : "61975", "user_id" : "100", "update_what" : "CC"}
### notification that a new user has been invited:
{ "notification_type": "case_user_invited", "bz_source_table": "ut_notification_case_invited", "notification_id": "6", "created_datetime" : "2018-06-11 14:50:29", "unit_id" : "289", "case_id" : "61975", "invitee_user_id" : "134"}

## The assignee to the case is changed:
We generate 2 notifications
### notification that something happened on that case:
{ "notification_type": "case_updated", "bz_source_table": "ut_notification_messages_cases", "notification_id": "194", "created_datetime" : "2018-06-11 14:22:35", "unit_id" : "32", "case_id" : "12345", "user_id" : "1", "update_what" : "AssignedTo"}

### notification for the new assignee:
{ "notification_type": "case_assignee_updated", "bz_source_table": "ut_notification_case_assignee", "notification_id": "3", "created_datetime" : "2018-06-11 14:22:35", "unit_id" : "32", "case_id" : "12345", "invitor_user_id" : "0", "assignee_user_id" : "1"}

## A case is updated (excl. change of assignee or new invited user:
### notification that something happened on that case:
{ "notification_type": "case_updated", "bz_source_table": "ut_notification_messages_cases", "notification_id": "202", "created_datetime" : "2018-06-11 14:50:29", "unit_id" : "289", "case_id" : "61975", "user_id" : "100", "update_what" : "CC"}

**Comment by franck-boullier** [comment]
@kaihendry 
"How do I know that I need to notify (...) Could that be made more obvious?"
This depends on the 
- notification type
- Whether the user has decided to opt out of these notification or not

Notification type: 
- case_assignee_updated -> notifiy the assignee_user_id
- case_assignee_new -> notifiy the assignee_user_id
- case_user_invited -> notify the invitee_user_id

Not sure how I can make it more obvious, happy to hear any suggestion.

**Comment by franck-boullier** [comment]
@kaihendry 
When the user has signed in for Unee-T for the first time, he/she is asked to opt-in for these notification
"How do I look up assignee_user_id's opted-in notification preferences"
Answer to this question is "check if the user has opted out from these notifications. If user has opted out, then do not notify the user"

**Comment by franck-boullier** [comment]
@kaihendry 
"What is the template (copy writing) of the message for email (or perhaps sms)"
We don't have one for now. My opinion on this is to keep it simple:
- Unee-T logo
- very factual and informative message similar to what we are doing when we invite a user to Unee-T the first time. See the ReadMe for https://github.com/unee-t/sns2email for what we want to do.

@kiatlim, if you have any recommendation, please let us know your thoughts

**Comment by kaihendry** [comment]
Will **notification_id**'s be unique across all types? For example if I looked up ""notification_id": "202"" i would know it was ""notification_type": "case_updated", "bz_source_table": "ut_notif... etc etc. ?

**Comment by franck-boullier** [comment]
@kaihendry "Will notification_id's be unique across all types?" 
The pair `notification_id`/`bz_source_table` is unique 
Warning there could be the same `notification_id` in different `bz_source_table`

You should look up  ""notification_id": "202" AND "bz_source_table": "ut_notification_case_assignee"" (or something to that effect) then you can return the `notification_type`

**Comment by kaihendry** [comment]
> Not sure how I can make it more obvious, happy to hear any suggestion.

Having { notify: 99 } to explicitly say who to notify? Want to avoid logic and mappings in my code ideally.
https://s.natalian.org/2018-06-12/nfeedback.mp4

**Comment by franck-boullier** [comment]
@kaihendry 
> Having { notify: 99 } to explicitly say who to notify? 

Ok will do the update in the notification.
I will also add the case title so that it is easy for you to get that too.

**Comment by franck-boullier** [comment]
Will also do the change in notification type when a new case is created too

**Comment by kaihendry** [comment]
The use case of an existing user being invited to the case I believe is fixed by @nbiton PR https://github.com/unee-t/frontend/pull/284

To re-iterate the discussion I had with @nbiton today. Notifications are best handled by Meteor.

I'm a little confused why we went down this route of using events from Bugzilla, when the Frontend IIUC had all the information to hand for this particular notification case.

Now there is a new issue https://github.com/unee-t/sns2email/issues/1 which probably should be three separate issues & prioritized accordingly.

**Comment by franck-boullier** [comment]
>The use case of an existing user being invited to the case I believe is fixed by @nbiton PR #284

Unfortunately no, this does NOT solve the issue:
A user can be invited to a case either from the MEFE or from the BZFE.
The method in PR #284 will only work if the existing user is invited to the case via the MEFE, nothing will happen if the user is invited via the BZFE/dashboard.

This is why we had to go through the lambda route: there is no other way to record invitations to a case which would originate from the BZF/Dashboard

> To re-iterate the discussion I had with @nbiton today. Notifications are best handled by Meteor.

That might be the case but we need to make sure that the MEFE is able to handle notification even if the event is initiated in the BZFE -> we need the lambda...

**Comment by franck-boullier** [comment]
For more details on the simplest notifications we need see:
- [Simplest notifications - A New user is invited to a case -> Notify the invited user](https://github.com/unee-t/sns2email/issues/3)
- [Simplest notifications - The user assigned to the case is changed - Notify the new assignee](https://github.com/unee-t/sns2email/issues/2) 
- [Simplest notifications - A new case is created - Notify the Assignee](https://github.com/unee-t/sns2email/issues/1)

**Comment by franck-boullier** [comment]
> Now there is a new issue unee-t/sns2email#1 which probably should be three separate issues (in Frontend)

@kaihendry Sorry to insist on this one but I am definitely confused: how will handling those in the front end be faster than what we discussed a few hours ago?
Please keep in mind that the method we need to implement should be able to handle these events regardless of which front end is used to originating from:
- the MEFE and/or 
- the BZFE

**Comment by kaihendry** [comment]
Well, it's been split into three bugs over at https://github.com/unee-t/sns2email, so I suppose so.
