### ISSUE TITLE
eMail for an invited user is incorrect or has a typo -> notifications are bouncing back

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/frontend#334]
# The problem:
When a user invites another user, there is a risk that the invitor enters an invalid email address for the invitee (typo, email address does not exists, etc...)

# Expected behavior:
In this scenario, we need to be able to identify these invalid emails to:
- Stop sending notification to that invalid email address
- Notify the invitor that the email he/she entered for the invitee is incorrect.

**Comment by kaihendry** [comment]
Going to assume this issue was fixed in #335.

The alternative approach of listening to SNS bounce notifications, isn't good since it takes about 12hrs for them to come back in my testing.

**Comment by franck-boullier** [comment]
#335 does not fix this
We need a mechanism to disable invalid emails even if it is done with delay.

Invalid emails are different from verified email.
An invalid email is an email which has been "confirmed as incorrect".
This is NOT the same as an unverified email: we don't know if an unverified email is valid or not and we need a way to record that an unverified email is invalid.

**Comment by kaihendry** [comment]
Ok, I can make the "bouncing" lambda SNS to POST into the MEFE with an email address that's bouncing.

@nbiton I proposed an API on Postman

<img src="https://s.natalian.org/2018-06-28/1530150363_2558x1406.png">

We might need to think about the UX where the email address is temporarily bouncing. E.g. mailbox is full over a weekend.

So what's the logic? I post the failing email address, MEFE looks that up from the User collection and marks every email it finds as being unverified again? Or another attribute, failing ?

**Comment by nbiton** [comment]
In this scenario (initial invitation), the email will not be verified in the first place, since the user never had the chance to do that. We will need a different attribute, possibly on the invitation so the invitor could track it. 

> We might need to think about the UX where the email address is temporarily bouncing. E.g. mailbox is full over a weekend.

Really not sure what to do about that...

**Comment by franck-boullier** [comment]
To know which attribute needs to be updated when an email is verified as invalid (bounced back for instance) see Issue #330.

**Comment by kaihendry** [comment]
We should de-prioritise this as we won't be sending emails to unverified emails going forward. I am tracking SNS bounces, so if this does indeed become a problem, we should revisit this.

**Comment by kaihendry** [comment]
Ok, so the scenario is that a user invites "invalid@example.com". Email bounces. We get the notification ~12hrs after via a AWS SES event.

In the MongoDB, it will look like:

```
{ "_id" : "z9BscsJzqRpKX8A6b", "bugzillaCreds" : { "login" : "invalid@example.com", "password"
: "aarUiiuxgK7!", "apiKey" : "KSkG5MImDyvLRAma", "id" : 23 }, "createdAt" : ISODate("2018-07-04T02:38:54.933Z"), "services" : {  }, "emails" : [ { "address" : "invalid@example.com", "verified" : false } ], "profile" : { "isLimited" : true }, "notificationSettings" : { "assignedNewCase" : true, "assignedExistingCase" : true, "invitedToCase" : true, "caseNewMessage" : true, "caseUpdate" : false }, "receivedInvites" : [ { "invitationId" : "o5mD77XQwo9DZCnKd", "role" : "Contractor", "isOccupant" : false, "caseId" : 1, "unitId" : 1, "invitedBy" : "gFLza3AoELnSdYnre", "timestamp" : 1530671935039, "type" : "type_cc", "accessToken" : "qhrRipO8wHAqXGZ985EfVAIz", "done" : true } ] }
```

So in `"emails" : [ { "address" : "invalid@example.com", "verified" : false } ]` do we want to create a new attribute, **invalid**?

And **invalid** would be mean that email is of [bounce Type **Permanent**](https://docs.aws.amazon.com/ses/latest/DeveloperGuide/notification-contents.html#bounce-types). I.e. we **ignore Transient** bounce failures?

What happens if someone else invites an invalid user? Ignored?

Do we remove invalid users?

**Comment by franck-boullier** [comment]
> So in "emails" : [ { "address" : "invalid@example.com", "verified" : false } ] do we want to create a new attribute, invalid?

I like that approach

> And invalid would be mean that email is of bounce Type Permanent. I.e. we ignore Transient bounce failures?

I think that would be a good start yes

> What happens if someone else invites an invalid user? 

Not sure I understand the question :thinking: can you please clarify @kaihendry?

> Do we remove invalid users?

No: we just mark the email as invalid and devise a way to prompt/notify the invitor that the email he used in his/her invitation is invalid/bouncing back

**Comment by kaihendry** [comment]
Just asking what is expected to happen when someone also invites the same invalid in email. I guess the UI will fail saying that email is known to be invalid or something.

I can implement the lambda to call into the Frontend, but an Frontend endpoint needs to be defined in Postman IIUC to will basically take an email address and mark it as invalid. Sound sensible @nbiton ? I can have a go at implementing this.

**Comment by franck-boullier** [comment]
> I guess the UI will fail saying that email is known to be invalid or something.

This sounds reasonable...

**Comment by nbiton** [comment]
Do you mean implementing an endpoint for MEFE? sounds like a good approach.
What do you mean by 
> an Frontend endpoint needs to be defined in Postman IIUC

?

**Comment by kaihendry** [comment]
@nbiton I've defined an API in Postman already: "Mark email as bouncing". That's what I mean by endpoint. Since I can't write direct into the MongoDB, can I?

**Comment by nbiton** [comment]
Technically you can, but it will be bad, and I won't like it :sweat_smile: 
Which is why I said 
> Do you mean implementing an endpoint for MEFE? sounds like a good approach.

:+1:

**Comment by kaihendry** [comment]
Btw, I've tested this on dev. This appears to work.

However a [new bug](https://github.com/unee-t/frontend/issues/362) probably should be created to "devise a way to prompt/notify the inviter that the email he used in his/her invitation is invalid/bouncing back"
